AllCops:
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/LineLength:
  Max: 240

Metrics/MethodLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/ClassVars:
  Enabled: false
