AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/LineLength:
  Max: 240

Metrics/MethodLength:
  Max: 30
